database:
  image: mariadb
  volumes:
    - /opt/jardinfaq/dbdata/:/var/lib/mysql:rw
    - ./extras/docker-compose/mysql_conf.d/:/etc/mysql/conf.d

redis:
  image: redis

mta:
  image: tozd/postfix

middleware:
  image: zulupro/jardinfaq
  command: uwsgi --ini /conf/uwsgi.ini
  ports:
    - "127.0.0.1:30310:3031"
  links:
    - database
    - redis
    - mta
  volumes:
    - /var/www/jardinfaq/static/:/static/
    - /var/www/jardinfaq/media/:/media/
    - /opt/jardinfaq/conf/:/conf/
    - .:/jardinfaq/

celery:
  image: zulupro/jardinfaq
  command: ./manage.py celery worker -l info
  links:
    - database
    - redis
    - mta
  volumes:
    - /var/www/jardinfaq/static/:/static/
    - /var/www/jardinfaq/media/:/media/
    - /opt/jardinfaq/conf/:/conf/

celerybeat:
  image: zulupro/jardinfaq
  command: ./manage.py celerybeat
  links:
    - database
    - redis
    - mta
  volumes:
    - /var/www/jardinfaq/static/:/static/
    - /var/www/jardinfaq/media/:/media/
    - /opt/jardinfaq/conf/:/conf/
